### ISSUE TITLE
App Crashes if Mac Isn't Bound to Domain

### ISSUE THREAD

**Issue by bahhhhh** [joshua-d-miller/LAPS-for-macOS#2]
The app crashes after entering a computer name and clicking on 'Get Password' if the Mac isn't bound to a domain. Below is crash log.

[log.txt](https://github.com/joshua-d-miller/LAPS-for-macOS/files/2829338/log.txt)

Suggestion: maybe have the app check if the Mac is bound to a domain, and if it isn't, have a message appear saying something along the lines of "Your Mac has to be bound to a domain for this app to work".

**Comment by joshua-d-miller** [comment]
Hi there! I'm so sorry it took a while to resolve this but I have gone ahead and updated the logic to look for if the machine is bound to Active Directory. The latest release should resolve your issue.

Thanks!
