### ISSUE TITLE
"Unable to retrieve Computer Record" for any computer

### ISSUE THREAD

**Issue by walkintom** [joshua-d-miller/LAPS-for-macOS#3]
I know it's terribly vague but I'm receiving "Unable to retrieve Computer Record" for any computer on our domain from my domain-joined admin machine. Is there any logging or debugging I could enable to try and trace the cause?
![Screenshot 2019-08-21 at 09 36 30](https://user-images.githubusercontent.com/6242598/63416622-adb26980-c3f7-11e9-9c79-ec8df77bfb2a.png)

**Comment by joshua-d-miller** [comment]
Hi there! The only thing that is required is to make sure the account under credentials has access to retrieve passwords. Can you verify that the account saved under credentials does have the ability to pull LAPS passwords?

**Comment by walkintom** [comment]
It definitely does, yeah. I've also tried prefixing the domain in front of the username too. Does the AD OU structure matter at all?

**Comment by joshua-d-miller** [comment]
So I experienced this issue yesterday and this morning I'm not. I'm not sure why that would matter but after rebooting it seems to have resolved. I'm going to dive into the code to figure out why this is happening.

**Comment by walkintom** [comment]
So, I'm not sure whether this is a problem with the app to be honest. With the app, I can't see any computer record; I've tried domain\computername, FQDN, computername$ to reflect the SAM account name but na-da.

If I DSCL query via Terminal with `dscl /Active\ Directory/domain/All\ Domains -read /Computers/computername$ dsAttrTypeNative:ms-Mcs-AdmPwd` it returns `No such key: dsAttrTypeNative:ms-Mcs-AdmPwd` even if I switch user and run it as an admin that can see the LAPS password via the Windows AD GUI.

But then I'm not sure if the two are linked, I had a look through the app code and figured if I couldn't see the attribute via DSCL, the app probably wouldn't see it either.

**Comment by joshua-d-miller** [comment]
@walkintom So by default that is hidden using directory utility or dscl. Basically, by default in AD, the computer can write the record but it can't read it. I guess next steps would be to verify that the same user you are using can see it using the Windows LAPS utility or see the password via ADSI Edit.

**Comment by walkintom** [comment]
Can’t say I’ve ever used ADSI Edit but the Windows LAPS utility is working fine as the users I’ve tried LAPS for macOS with (albeit it with some annoyance as I have to run it as a remote app).

**Comment by joshua-d-miller** [comment]
@walkintom So I was looking at this issue again and it looks like you said you were prefixing your account with the domain? You should not need to do that as if you are running this on a bound machine you would only need to enter credentials via username and password.

**Comment by walkintom** [comment]
@joshua-d-miller funnily enough, I’ve been meaning to update this issue. I switched to a new machine earlier in the week, still joined to the same AD domain, same setup and configuration, and LAPS for macOS now works as expected. On my old machine, it still doesn’t. Extremely strange and other than the hardware, there isn’t any difference between them. So we might never know why, but I’m happy for this issue to be closed!
